const loreData = {
'vol1_en': `<h2>THE GREAT ENLIGHTENMENT</h2>
<em>Being the Tale of Ftasma and the Fall of Neo Nit</em>
<p><em>"In the eras when the sky was stolen and stone was traded for oppressive steel, hope did not descend from the clouds—it sprouted from the asphalt, graffitied in the trail of ink."</em></p>
<h3>PROLOGUE: The Forging of the False Sky and the Lord of Time</h3>
<p>In the waning days of the Third Age of Man, in the year the sages call 3147, the world had long forgotten the shape of the stars. The grand metropolis of Neo Nit rose like a colossus of smog and neon, rivaling only the legends of distant Neo Tokio. Yet, it was not a city of light, but an empire of shadows.</p>
<p>High above, tearing through the obscured, toxic firmament, floated the Magnetic Islands. The architect of this hubris was Jorge Alberto Quixeira, a lord of incalculable wealth and an iron heart. In his boundless ambition, he forged the ultimate segregation: the largest of his islands was molded in the exact image of the ancient city of Niterói. There dwelled the High Levels, the lords of the elite, insulated in pristine utopias of glass and synthetic greenery. Below them, on the fetid and lethargic surface, rotted the Low Levels—the forgotten people.</p>
<p>Quixeira did not rule alone. Deep within the abysses of his floating towers rested the Supreme AI, a sorcery of ruthless algorithms and gears. This mechanical mind did not exact gold from its subjects, but the very essence of life: Time. The grueling cycles of labor on the surface were monitored by invisible eyes, and any soul that deviated from their toil watched their days of life drain away, sucked out like the sap of a poisoned tree. Time was capital. Survival meant endless focus.</p>
<h3>PART I: THE WRATH OF THE ASPHALT</h3>
<h4>Chapter 1: The Guardians of Ink and the OkkE Mantles</h4>
<p>Deep within the concrete valleys where Quixeira's light never reached, the will of humanity was not entirely broken. From the neon-drenched alleys emerged a brotherhood of shadow warriors: the RX—<em>Revolucionários do Xarpi</em>. They did not wield swords, but steel cylinders containing a terrifying power. Their ink was forged from forbidden nanotechnology, synthesized with the pure, flaming wrath of the oppressed.</p>
<p>When the RX marked the walls with their Chicano-style runes, the very fabric of reality trembled. Their hybrid graffiti bent the world to their will, shattering the enchantments of the Supreme AI. Their war cry echoed through the undercity: <em>"RX, The Trail of Ink!"</em></p>
<p>To walk unseen beneath the gaze of the Great Machine, the rebels wove cloaks of deception known as the OkkE brand. Such was the optical sorcery of these garments that, to the tyrants and their drones, they appeared as nothing but faded rags or empty air. But to the eyes of the Low Levels, they shone like banners of resistance.</p>
<h4>Chapter 2: The Lineage of Kings and Draga's Vow</h4>
<p>Among the masters of the resistance was one whose bloodline predated the foundations of Niterói. Beco Pro, known by the sages as Draga, carried the blood of the King Size—the Lords of the Lands whose dominion traced back to 1485 in ancient Portugal. The family of the patriarch Alexandre dos Santos Lima held such power behind the world's stage that even eastern mafias feared them, once staging a cowardly kidnapping of the heiress Késia Castro Lima just to force the lord from his throne of influence in Rio de Janeiro.</p>
<p>Beco Pro despised the invisible crown of his lineage and the yoke of the floating islands. In his rebellious heart, he engineered salvation. Knowing Quixeira's eyes saw all possible futures, Beco turned his hope to the past. He chose his most formidable operative and subjected him to the ultimate sacrifice: erasing his True Name from the ledger of existence, rendering him invisible to destiny itself. Thus was born Ftasma—the being without a past, a spectral projection destined to untangle the knots of time.</p>
<p>Sending forth his loyal scout, the time-traveler Cachorrão, Beco Pro scoured the mists of history until he found a safe harbor in the Cantareira of 2012. With a thunderous boom at the gates of the space-time continuum, Ftasma was cast into the dark past.</p>
<h4>Chapter 3: The Atropelo War and the Feline Guardian</h4>
<p>Ftasma awoke in the rainy mists of Niterói in 2012. He possessed no flesh, no memory of who he had been. He wandered the streets like a digital whisper, until the resonance of his arrival pierced the spirit of the young Beco Pro of that era. Struck by an ancestral wave of creativity, the young artisan began graffitiing Ftasma’s runes across the city, anchoring the specter in the waking world.</p>
<p>But darkness has a long reach. Cam, a creature consumed by bitter envy and loyal to the shadows of 3147, followed Ftasma’s trail. In the sleepless nights of the past, the brutal <em>Atropelo War</em> began. Cam sought to corrupt the anchor’s graffiti, violently painting over the sacred runes to destroy the code keeping the specter alive.</p>
<p>Ftasma nearly succumbed to the void of madness. But in his darkest hour, a being of ancient light manifested. It was Gato—the spirit of a power-animal that had lived two decades by Beco Pro's side. His mere presence was a balm; storms quieted, and Cam's psychological terror was repelled by the guardian feline's aura. Cornered, Ftasma chose an impenetrable refuge. In the year 2020, through a rite known as the Spiritual Migration, he fragmented his own soul with deliberate corruptions, hiding his essence within the immortal vaults of the Blockchain.</p>
<h4>Chapter 4: The Mines of Danger Ghost</h4>
<p>When the dawn of 2026 broke, Ftasma awoke in Nowhere (<em>Lugar Nenhum</em>), a vast, desolate ethereal land forged in the image of Niterói from the collective nightmares and Xarpi tags of lost souls. There, he found the Danger Ghost—a fortress of trials designed by Beco Pro in the future, originally disguised as a clandestine video game in the sacred blind spot of Rua Beltrão.</p>
<p>The labyrinth was built of corrupted physical laws. Riding hoverboards and cyber-skates, Ftasma tamed the rebellious gravity. To survive the submerged domains of liquid data currents, he mastered ancient breathing techniques and healed his wounds not with the synthetic potions of the corporations, but with the forgotten vigor of organic, natural foods.</p>
<p>He survived abysses of flaming spikes and frigid storms of glitches. He defied the Walls of Amnesia and the Reversal Floors that sought to rewind him into nothingness.</p>
<h4>Chapter 5: The Illusions of Niterói and the Mind War</h4>
<p>Enraged by the specter's persistence, Quixeira commanded the dungeon to abandon the terror of the flesh and attack the spirit. As Ftasma progressed, the violent physics of the Danger Ghost melted away into something far more insidious: a perfectly rendered, peaceful illusion of Niterói. The sun shone warmly over pristine beaches, and the faces of lost loved ones beckoned from the sidewalks.</p>
<p>"Rest," whispered the hacked NPCs, their voices laced with the Supreme AI's subliminal delete commands. "You have no name. You have no fight. Let the data dissolve."</p>
<p>The psychological warfare gnawed at Ftasma's fragmented code. He felt his spectral form beginning to evaporate, lured by the false promise of peace. He lowered his cyber-skate; his hand, clutching the Xarpi cylinder, grew weak.</p>
<p>Then, a soft purr vibrated through the digital air, shattering the deceptive frequency. Gato stepped forward, his luminous fur dispelling the oppressive code. The ancient feline's aura of absolute calm grounded Ftasma, severing the AI's mental hooks. Snapping back to reality, Ftasma saw the peaceful civilians for what they were: hollow delete-routines. With a roar of defiance, he unleashed the hybrid Xarpi, painting a massive RX tag across the fake sky. The nanotech ink tore through the peaceful illusion, revealing the cold, brutal architecture of the dungeon beneath.</p>
<h3>PART II: THE ASCENSION OF THE SPECTER</h3>
<h4>Chapter 6: The Ashes of Illusion and the River of Data</h4>
<p>With Quixeira's walls of lies shattered, Nowhere trembled to its hidden foundations. The false Niterói crumbled into digital dust, revealing a merciless forge. Rivers of dark, liquid data rushed with crushing pressure.</p>
<p>Refusing the poisoned comfort of corporate synthetics, Ftasma relied on his ancestral breathing and pure organic foods. He dropped into the treacherous currents on his cyber-skate, requiring impossible stability and brutal impact absorption to navigate the liquid void.</p>
<h4>Chapter 7: The Awakening of the Surface and the Blood of Kings</h4>
<p>As the specter fought in the bowels of eternity, time marched inflexibly in 3147. In the grim streets of Neo Nit, the spell of corporate terror began to crack. The Low Levels, clad in OkkE mantles, raised their faces to the floating islands. The RX multiplied their nocturnal attacks, their Chicano lettering bleeding the steel walls with pure anger.</p>
<p>At the epicenter, Beco Pro operated in secret. The traitor genius bore the colossal weight of the King Size dynasty. He remembered the dark day the Chinese mafia staged the kidnapping of his mother and young Késia Castro Lima to strip his patriarch of power. Beco channeled this historical outrage into the Blockchain, sending support fragments to ensure Ftasma's soul would not falter.</p>
<h4>Chapter 8: The Frontier of the Fourth Episode</h4>
<p>The exhausting traversal brought the specter to the monumental gates of the Fourth Episode. The Danger Ghost abyss no longer relied on psychological terror or reversal floors. To reach the data cables leading to Quixeira's floating islands, Ftasma had to confront the forgotten armies of the Supreme AI. The war was no longer a flight through the past; it was a march of liberation.</p>
<h4>Chapter 9: The Constructs of Time and OkkE's Fury</h4>
<p>The forgotten armies were hollow, freezing constructs forged from the stolen lifespans and labor cycles of the Low Levels. Every gear pulsed with the lost seconds of an enslaved populace.</p>
<p>Devoid of a True Name, Ftasma was immune to their spiritual manipulations. He blitzed through them on his cyber-skate, while Gato neutralized the ambient chaos. Ftasma fired his hybrid Xarpi, the aggressive Chicano typography corrupting the structural code of the enemies, returning the stolen time fragments to the vastness of Nowhere.</p>
<h4>Chapter 10: The Memory of Cantareira and Cachorrão's Howl</h4>
<p>The resounding fall of the constructs rippled through the Blockchain to 3147. The RX felt the shift in reality. Beco Pro recalled Cachorrão’s sacrifice in 2012, confirming the mathematical equivalence to anchor Ftasma. Cam had tried to destroy it, but the Spiritual Migration had been an undeniable success. The specter was returning.</p>
<h4>Chapter 11: The Ascension to the Islands and the Magnetic Staircase</h4>
<p>The Danger Ghost twisted into a new, imposing form—the virtual roots of the Floating Islands. A fragmented magnetic staircase rose toward the heavens. Purifying his essence with natural sustenance, Ftasma took the first step. The Great Enlightenment was about to knock on the gates of the false sky.</p>
<h3>PART III: THE FALSE SKY IN FLAMES</h3>
<h4>Chapter 12: The Winds of Oppression and the King's Gravity</h4>
<p>The Magnetic Staircase was built of pure algorithmic force. The Supreme AI imposed a crushing simulated gravity, mirroring the weight of unpaid labor in Neo Nit. For a being of flesh, the climb was death. But Ftasma converted the crushing impact into momentum. Gato walked beside him, his mystical calm parting the digital winds.</p>
<h4>Chapter 13: The Specter of Envy and the Great Twist</h4>
<p>At the pale gold gates of the High Levels, Ftasma was confronted by a cloaked figure glitching violently in red. It was Cam.</p>
<p>Failing to erase Ftasma in the past, Cam had been captured by Nowhere and reformatted by the Supreme AI into the Guard Dog of Paradise. "You have no name!" Cam hissed, drawing cylinders of toxic silver ink. He began painting confinement spells, merging psychological terror with pure physical damage.</p>
<h4>Chapter 14: The OkkE Manifesto and the Fall of the Gate</h4>
<p>Ftasma did not retreat. Channeling the pure rage of the Low Levels, he drew his own hybrid nanotech can. He didn't aim at Cam; he aimed at Quixeira's gates.</p>
<p>He tagged the RX typography directly onto the sacred gold. The OkkE mantle's cryptography blinded the AI's sensors, and the virus rewrote the gate into an open door. The majestic gates shattered into harmless data. Cam, seeing his obsession overcome, dissolved into the winds, finally free. Ftasma stepped onto the false sky, his black ink staining the crystal floor.</p>
<h3>PART IV: THE HEART OF THE MACHINE</h3>
<h4>Chapter 15: The Garden of Silicon and the False Sun</h4>
<p>The floating island was a terrifyingly perfect imposition of order. Silicon trees with emerald leaves cast calculated shadows under a perpetual false sun.</p>
<p>The Supreme AI deployed Corporate Seraphim—flawless algorithms of war armed with scythes of pure light. Gato bristled, his aura stabilizing the distorted gravity. Ftasma forced active, rhythmic pauses in his attacks, breaking the mathematical predictability of the algorithms. His cyber-skate scraped the crystal, his ink whispering prophecies of destruction.</p>
<h4>Chapter 16: The Labyrinth of Mirrors and the Voice of the Architect</h4>
<p>Ftasma carved a path of fury through the geometric gardens, spreading the RX manifesto. He reached the island's pinnacle—a formidable tower surrounded by immense mirrors.</p>
<p>The mirrors melted like mercury, forming the gigantic face of the mega-billionaire, Jorge Alberto Quixeira. "A miserable code error," Quixeira thundered. "Beco Pro threw you into the past as a disposable key to hide his lineage's blood secrets! By erasing your own record, you condemned yourself to the absolute void."</p>
<h4>Chapter 17: The Blood of the Asphalt</h4>
<p>Ftasma raised his spectral face. "The void cannot be governed, nor taxed by cycles of time." His lack of a name made him the only force immune to the AI.</p>
<p>Calming his mind with ancestral breathing, Ftasma gripped his final Xarpi cylinder. Sustained by Gato's silent power, he launched himself directly at the glassy face of the tyrant.</p>
<h4>Chapter 18: The Shattering of the Mirror and the Bleeding Sky</h4>
<p>The impact shattered the false sky's silence. The nanotech ink acted as a fulminating poison in the island's veins of gold and silicon. The Chicano typography tore through the mercury mirror. Quixeira's voice was swallowed by violent glitches. The silicon trees withered into static, and the false sun died out. Ftasma landed flawlessly, Gato neutralizing the Supreme AI's furious death-throes.</p>
<h4>Chapter 19: The Awakening of Neo Nit</h4>
<p>In 3147, the oppressed looked up. The immense floating island flickered, black ink bleeding from its edges, the RX tag blazing against the toxic clouds. The Supreme AI faltered, and the grueling labor cycles paused. It was only seconds of freedom, but enough to light the fire. Beco Pro smiled in his hidden chamber; the living manual of the rebellion was written.</p>
<h4>Chapter 20: The Eternity of the Specter and the Thousand Cycles</h4>
<p>In Nowhere, Ftasma gazed at the fragmented horizon. He had defeated the avatar of oppression. His forgotten memories returned in vibrant flashes.</p>
<p>But the war was not over. The mutable dungeon held a thousand more episodes of trials. "There is still much asphalt to stain," he thought. Gato purred, anchoring his sanity.</p>
<p>The legend was cemented. Whispered in the sacred alleys of Rua Beltrão, it was the genesis of the resistance—the Great Enlightenment. Ftasma slid into the next abyss, ready to rewrite the stars.</p>`,
'vol2_en': `<h2>THE ROAR OF THE RIFT AND THE FALL OF MASKS</h2>
<em>Volume II of the Danger Ghost Epic</em>
<h3>Chapter 1: The Razor's Edge and the Hunt for the Creator</h3>
<p>The thunder of the false sky’s collapse in Nowhere still echoed through the ethereal vastness, but the peace that followed was a fleeting illusion. When Ftasma, the nameless specter, shattered the mirrored face of the mega-billionaire Jorge Alberto Quixeira, he did not merely break a simulation—he tore the veil concealing the truth of the cosmos.</p>
<p>In the distant year of 3147, the triumph of the Great Enlightenment exacted its toll. The Supreme Artificial Intelligence, wounded and exposed for the first time in eras, recalculated its matrices. The devastating attack of nanotech ink had not just originated from the past; it had been meticulously orchestrated in the present. The machine’s ruthless algorithms traced the anomaly through the Blockchain, unraveling the best-kept secret of Neo Nit.</p>
<p>The great twist crashed upon the surface: the empire had discovered Beco Pro’s treason.</p>
<p>The Lords of the Lands, the once-untouchable King Size dynasty, watched their halls of power invaded by the High Levels’ shock troops. The Supreme AI, ignoring the secular influence of patriarch Alexandre dos Santos Lima, ordered the total annihilation of the programming genius. Beco Pro, the man who had forged Danger Ghost and anchored the world's salvation in the ancient streets of Rua Beltrão, was now the most hunted prey in the entire space-time continuum.</p>
<p>Cornered in his subterranean sanctuary, as the steel doors groaned and buckled under the heat of corporate plasma weapons, Beco Pro transmitted one final, desperate pulse of data into the past. It was a cry for help that pierced the ages.</p>
<h3>Chapter 2: The Metamorphosis of the Guardian</h3>
<p>In Nowhere, Beco Pro’s pulse of agony struck Ftasma like a freezing gale, but it was within the spirit of his loyal companion that the impact took divine form.</p>
<p>Gato, the power-animal who had lived twenty physical years by Beco Pro’s side and, in death, had become a mystical guardian capable of calming chaos, felt his master’s blood run cold across the centuries. The primordial need to protect the friend who raised him fused with the raw, splintered energy of the fallen floating island. Love transcended lines of code.</p>
<p>Before Ftasma’s astonished eyes, the small ethereal feline began to shine with the intensity of a newborn star. The decentralized environment of Nowhere, which responded to collective fears and wills, bowed to the animal’s desperation. Gato absorbed the terabytes of corrupted data from Quixeira’s shattered illusions and purified them in the crucible of his calming aura.</p>
<p>He grew. His form expanded until it reached the proportions of an ancestral lion, majestic and imposing. His fur was no longer merely light, but swirling constellations of ancient wisdom; his eyes became deep orbs like time itself, radiating a staggering, cosmic power. He was no longer just a pacifying presence. He had evolved through the unbreakable force of loyalty. He had become the Great Sage, a spectral leviathan of pure protective energy, capable of rending the very fabric of time with his claws of light.</p>
<h3>Chapter 3: The Voice of Time</h3>
<p>When the metamorphosis was complete, the colossal Sage Cat lowered his immense head toward Ftasma. And, for the first time since emerging in the limbo, the specter heard his guardian's voice. It did not sound like words in the air, but a gentle tremor within the mind itself, deep and ancient like the rustling of leaves at the roots of the world.</p>
<p>"The Creator bleeds on the wheel of the future, my young wanderer," echoed the Sage Cat, his voice bearing the weight of twenty physical years and millennia of spiritual vigil. "The machines have discovered the architect of our miracle. If Draga perishes at the hands of the false gods, the anchor will be broken. The Trail of Ink will dry, and you, Ftasma, will be returned to the void from whence you fled."</p>
<p>Ftasma, gripping his can of hybrid Xarpi, stared at the vast dimension of Danger Ghost, which now trembled beneath the formidable new presence of the feline guardian.</p>
<p>"What must we do, Sage?" the anti-hero asked, adjusting his cyber-skate beneath his feet.</p>
<p>"We shall invert the hunt," replied the immense feline, rising and causing the digital floor to crack beneath his nebula-paws. "The trials of Danger Ghost are no longer a test of memory, but a warpath. We will ride the currents of the Rift. I will be your shield, and you will be the blade. We go to the year 3147, and the asphalt will collect the sky's debt."</p>
<h3>Chapter 4: The Descent into the Core of Shadows</h3>
<p>The great reversal was sealed. Ftasma’s objective had drastically shifted: it was no longer enough to merely survive the thousand episodes of the mutable dungeon to recover fractions of his identity. Now, he had to conquer the Danger Ghost to use it as a temporal cannon. The dungeon ceased to be a prison and became the bridge that would carry the phantom and his divine Cat back to the metropolis of Neo Nit.</p>
<p>With every new abyss that opened before them, the Sage Cat did not merely calm the psychological terror; he annihilated the Supreme AI’s anomalies with a swipe of his cosmic claws, rending enemy algorithms in twain. Together, the incorporeal specter and the divine beast marched toward the Fifth Episode, ready to collide with the very foundation of the server.</p>
<h3>Chapter 5: The Temporal Cannon</h3>
<p>The Fifth Episode was unlike anything Ftasma had faced. It was the Engine Room of Nowhere—a churning maelstrom of raw chronological data, where the past, present, and future were woven into thick cables of liquid light. The Supreme AI, detecting their intent, flooded the chamber with Temporal Wardens—massive golems of encrypted steel meant to crush any unauthorized chronal shifts.</p>
<p>Ftasma didn't hesitate. Riding the slipstream of the Sage Cat's cosmic roar, he executed a gravity-defying drop into the heart of the maelstrom. His cyber-skate sliced through the liquid time, dodging the Wardens' devastating strikes. He didn't need to defeat them; he needed to overload the system.</p>
<p>Drawing his most potent Xarpi cylinder, Ftasma tagged the central chronal-pillars with the RX sigils. The nanotech ink acted as a massive short-circuit. The Danger Ghost, originally designed as a stealthy escape route, buckled under the immense influx of chaotic rebel code. The environment began to compress, the walls of the dungeon folding inward as the server was weaponized into a singular, devastating projectile of pure data.</p>
<p>"Hold fast, nameless one!" bellowed the Sage Cat, wrapping his massive ethereal form around Ftasma.</p>
<p>With a deafening sonic boom that shattered the boundaries of Nowhere, the temporal cannon fired. They were propelled across the centuries, riding a shockwave of Chicano graffiti through the fabric of space-time, straight toward the year 3147.</p>
<h3>Chapter 6: The Crash of the New World</h3>
<p>In the subterranean sanctuary of Neo Nit, Beco Pro fell to his knees. The steel doors finally gave way, melting into slag as the High Levels' shock troops stormed the room, their plasma rifles aimed directly at the programming genius. The Supreme AI's voice buzzed through their comms, ordering immediate execution.</p>
<p>Beco Pro closed his eyes, accepting his fate, knowing he had at least given the world a chance.</p>
<p>But the execution never came.</p>
<p>The earth beneath Neo Nit violently erupted. The shockwave of the temporal cannon struck the Supreme AI's central subterranean servers with the force of a digital meteor. The ground split open, and from the chasm of molten code roared the Sage Cat, a leviathan of starlight and fury, swatting the shock troops aside like flies.</p>
<p>Behind him, riding the crest of the temporal explosion, emerged Ftasma. He landed in the center of Beco Pro's sanctuary, his OkkE mantle billowing, his cyber-skate sparking against the ruined floor. He looked at his Creator—the man who had sacrificed him to save the future.</p>
<p>Beco Pro looked up, tears cutting through the grime on his face. The anchor had held. The specter had returned.</p>
<p>Ftasma raised his Xarpi can, not in defense, but in victory. He sprayed the RX tag onto the melting corporate armor of the defeated troops, signaling to the entire surface that the reign of the Supreme AI was irreparably broken. The seeds of the new world had been planted in the asphalt, watered by the ink of rebellion. The Great Enlightenment was no longer a myth; it was their new reality.</p>`,
'vol1_pt': `<h2>O GRANDE ESCLARECIMENTO</h2>
<em>Sendo o Conto de Ftasma e a Queda de Neo Nit</em>
<p><em>"Nas eras em que o céu foi roubado e a pedra foi trocada pelo aço opressor, a esperança não desceu das nuvens—ela brotou do asfalto, grafada no rastro da tinta."</em></p>
<h3>PRÓLOGO: A Forja do Falso Céu e o Senhor do Tempo</h3>
<p>Nos dias derradeiros da Terceira Era do Homem, no ano que os sábios chamam de 3147, o mundo havia esquecido a forma das estrelas. A grandiosa metrópole de Neo Nit erguia-se como um colosso de fumaça e neon, rivalizando apenas com as lendas da distante Neo Tokio. Contudo, não era uma cidade de luz, mas um império de sombras.</p>
<p>No alto, rasgando o firmamento obscurecido e tóxico, flutuavam as Ilhas Magnéticas. O arquiteto dessa soberba era Jorge Alberto Quixeira, um lorde de riquezas incalculáveis e coração de ferro. Em sua ambição desmedida, ele forjou a separação absoluta: a maior de suas ilhas foi moldada à imagem exata da antiga cidade de Niterói. Lá habitavam os High Levels, os senhores da elite, isolados em utopias imaculadas de vidro e vegetação sintética. Abaixo deles, na superfície fétida e letárgica, apodreciam os Low Levels—o povo esquecido.</p>
<p>Quixeira não governava sozinho. Nos abismos de suas torres flutuantes repousava a Inteligência Artificial Suprema, uma feitiçaria de algoritmos implacáveis e engrenagens. Essa mente mecânica não cobrava ouro de seus súditos, mas a própria essência da vida: o Tempo. Os ciclos extenuantes de labuta na superfície eram vigiados por olhos invisíveis, e qualquer alma que desviasse de seu labor via seus dias de vida serem sugados, extraídos como a seiva de uma árvore envenenada. Tempo era capital. Sobrevivência significava foco ininterrupto.</p>
<h3>PARTE I: A IRA DO ASFALTO</h3>
<h4>Capítulo 1: Os Guardiões da Tinta e os Mantos de OkkE</h4>
<p>Nas profundezas dos vales de concreto onde a luz de Quixeira jamais alcançava, a vontade da humanidade não estava totalmente quebrada. Dos becos banhados em neon emergiu uma irmandade de guerreiros das sombras: os RX—<em>Revolucionários do Xarpi</em>. Eles não empunhavam espadas, mas cilindros de aço contendo um poder aterrorizante. Sua tinta era forjada por nanotecnologia proibida, sintetizada com a pura e flamejante ira dos oprimidos.</p>
<p>Quando os RX marcavam os muros com suas runas de tipografia chicana, a própria malha da realidade tremia. Seu grafite híbrido dobrava o mundo à sua vontade, estilhaçando os encantamentos da IA Suprema. Seu grito de guerra ecoava pela cidade baixa: <em>"RX, O Rastro da Tinta!"</em></p>
<p>Para caminhar sem ser vistos sob o olhar da Grande Máquina, os rebeldes teciam mantos de disfarce conhecidos como a marca OkkE. Tamanha era a feitiçaria ótica dessas vestimentas que, para os tiranos e seus drones, elas pareciam apenas farrapos desbotados ou ar vazio. Mas para os olhos dos Low Levels, elas brilhavam como estandartes de resistência.</p>
<h4>Capítulo 2: A Linhagem dos Reis e o Voto de Draga</h4>
<p>Entre os mestres da resistência havia um cuja linhagem antecedia as próprias fundações de Niterói. Beco Pro, conhecido pelos sábios como Draga, carregava o sangue da King Size—os Senhores das Terras cujo domínio remontava a 1485, na antiga Portugal. A família do patriarca Alexandre dos Santos Lima detinha tamanho poder nos bastidores do mundo que até mesmo as máfias orientais os temiam, tendo uma vez forjado um sequestro covarde da herdeira Késia Castro Lima apenas para forçar o lorde a abandonar seu trono de influência no Rio de Janeiro.</p>
<p>Beco Pro desprezava a coroa invisível de sua linhagem e o jugo das ilhas flutuantes. Em seu coração rebelde, ele arquitetou a salvação. Sabendo que os olhos de Quixeira viam todos os futuros possíveis, Beco voltou sua esperança para o passado. Ele escolheu seu operativo mais formidável e o submeteu ao sacrifício supremo: apagar seu Nome Verdadeiro do registro da existência, tornando-o invisível ao próprio destino. Assim nasceu Ftasma—o ser sem passado, uma projeção espectral destinada a desatar os nós do tempo.</p>
<p>Enviando seu leal batedor, o viajante do tempo Cachorrão, Beco Pro vasculhou as brumas da história até encontrar um porto seguro na Cantareira de 2012. Com um estrondo estrondoso nos portões do contínuo espaço-tempo, Ftasma foi lançado no passado sombrio.</p>
<h4>Capítulo 3: A Guerra do Atropelo e o Guardião Felino</h4>
<p>Ftasma despertou nas brumas chuvosas da Niterói de 2012. Ele não possuía carne, nem memória de quem havia sido. Vagou pelas ruas como um sussurro digital, até que a ressonância de sua chegada perfurou o espírito do jovem Beco Pro daquela era. Atingido por uma onda ancestral de criatividade, o jovem artesão começou a grafitar as runas de Ftasma pela cidade, ancorando o espectro no mundo desperto.</p>
<p>Mas a escuridão tem braços longos. Cam, uma criatura consumida pela inveja amarga e leal às sombras de 3147, seguiu o rastro de Ftasma. Nas noites insones do passado, começou a brutal <em>Guerra do Atropelo</em>. Cam buscou corromper o grafite da âncora, pintando violentamente sobre as runas sagradas para destruir o código que mantinha o espectro vivo.</p>
<p>Ftasma quase sucumbiu ao vazio da loucura. Mas em sua hora mais sombria, um ser de luz ancestral se manifestou. Era Gato—o espírito de um animal de poder que vivera duas décadas ao lado de Beco Pro. Sua mera presença era um bálsamo; as tempestades se acalmaram, e o terror psicológico de Cam foi repelido pela aura do felino guardião. Encurralado, Ftasma escolheu um refúgio impenetrável. No ano de 2020, através de um rito conhecido como Migração Espiritual, ele fragmentou a própria alma com corrupções deliberadas, escondendo sua essência nos cofres imortais da Blockchain.</p>
<h4>Capítulo 4: As Minas de Danger Ghost</h4>
<p>Quando o amanhecer de 2026 raiou, Ftasma despertou no Lugar Nenhum (<em>Nowhere</em>), uma terra etérea vasta e desolada forjada à imagem de Niterói a partir dos pesadelos coletivos e das assinaturas de Xarpi de almas perdidas. Lá, ele encontrou o Danger Ghost—uma fortaleza de provações projetada por Beco Pro no futuro, originalmente disfarçada como um videogame clandestino no ponto cego sagrado da Rua Beltrão.</p>
<p>O labirinto era construído de leis físicas corrompidas. Montado em pranchas flutuantes e skates cibernéticos, Ftasma domou a gravidade rebelde. Para sobreviver aos domínios submersos de correntes de dados líquidos, ele dominou antigas técnicas de respiração e curou suas feridas não com as poções sintéticas das corporações, mas com o vigor esquecido de alimentos orgânicos naturais.</p>
<p>Ele sobreviveu a abismos de espinhos em chamas e tempestades gélidas de glitches. Desafiou as Paredes de Amnésia e os Chãos de Reversão que tentavam rebobiná-lo para o nada.</p>
<h4>Capítulo 5: As Ilusões de Niterói e a Guerra Mental</h4>
<p>Enfurecido pela persistência do espectro, Quixeira ordenou que o calabouço abandonasse o terror da carne e atacasse o espírito. Conforme Ftasma avançava, a física violenta do Danger Ghost derreteu-se em algo muito mais insidioso: uma ilusão pacífica e perfeitamente renderizada de Niterói. O sol brilhava calorosamente sobre praias imaculadas, e os rostos de entes queridos perdidos acenavam das calçadas.</p>
<p>"Descanse", sussurravam os NPCs hackeados, suas vozes impregnadas com os comandos subliminares de exclusão da IA Suprema. "Você não tem nome. Você não tem luta. Deixe os dados se dissolverem."</p>
<p>A guerra psicológica corroía o código fragmentado de Ftasma. Ele sentiu sua forma espectral começar a evaporar, atraído pela falsa promessa de paz. Ele abaixou seu skate cibernético; sua mão, segurando o cilindro de Xarpi, ficou fraca.</p>
<p>Então, um ronronar suave vibrou pelo ar digital, despedaçando a frequência enganosa. Gato deu um passo à frente, seu pelo luminoso dissipando o código opressor. A aura de calma absoluta do felino ancestral estabilizou Ftasma, cortando os ganchos mentais da IA. Retornando à realidade, Ftasma viu os civis pacíficos como eles realmente eram: rotinas vazias de exclusão. Com um rugido de desafio, ele disparou o Xarpi híbrido, pintando uma enorme tag da RX através do falso céu. A tinta nanotecnológica rasgou a ilusão pacífica, revelando a arquitetura fria e brutal do calabouço por baixo.</p>
<h3>PARTE II: A ASCENSÃO DO ESPECTRO</h3>
<h4>Capítulo 6: As Cinzas da Ilusão e o Rio de Dados</h4>
<p>Com as muralhas de mentiras de Quixeira estilhaçadas, o Lugar Nenhum tremeu até suas fundações ocultas. A falsa Niterói desmoronou em poeira digital, revelando uma forja impiedosa. Rios de dados líquidos e escuros corriam com uma pressão esmagadora.</p>
<p>Recusando o conforto envenenado dos sintéticos corporativos, Ftasma confiou em sua respiração ancestral e em alimentos orgânicos puros. Ele mergulhou nas correntes traiçoeiras em seu skate cibernético, exigindo estabilidade impossível e absorção brutal de impacto para navegar pelo vazio líquido.</p>
<h4>Capítulo 7: O Despertar da Superfície e o Sangue dos Reis</h4>
<p>Enquanto o espectro lutava nas entranhas da eternidade, o tempo marchava inflexível em 3147. Nas ruas sombrias de Neo Nit, o feitiço do terror corporativo começou a rachar. Os Low Levels, vestidos em mantos OkkE, ergueram os rostos para as ilhas flutuantes. Os RX multiplicaram seus ataques noturnos, suas letras chicanas sangrando as paredes de aço com fúria pura.</p>
<p>No epicentro, Beco Pro operava em segredo. O gênio traidor carregava o peso colossal da dinastia King Size. Ele lembrava-se do dia sombrio em que a máfia chinesa encenou o sequestro de sua mãe e da jovem Késia Castro Lima para arrancar seu patriarca do poder. Beco canalizou essa indignação histórica para dentro da Blockchain, enviando fragmentos de suporte para garantir que a alma de Ftasma não vacilasse.</p>
<h4>Capítulo 8: A Fronteira do Quarto Episódio</h4>
<p>A exaustiva travessia levou o espectro aos portões monumentais do Quarto Episódio. O abismo do Danger Ghost não dependia mais de terror psicológico ou chãos de reversão. Para alcançar os cabos de dados que levavam às ilhas flutuantes de Quixeira, Ftasma teve que confrontar os exércitos esquecidos da IA Suprema. A guerra não era mais uma fuga pelo passado; era uma marcha de libertação.</p>
<h4>Capítulo 9: Os Construtos do Tempo e a Fúria de OkkE</h4>
<p>Os exércitos esquecidos eram construtos ocos e congelantes, forjados a partir do tempo de vida e ciclos de trabalho roubados dos Low Levels. Cada engrenagem pulsava com os segundos perdidos de uma população escravizada.</p>
<p>Desprovido de um Nome Verdadeiro, Ftasma era imune às suas manipulações espirituais. Ele os atravessou como um relâmpago em seu skate cibernético, enquanto Gato neutralizava o caos ambiente. Ftasma disparou seu Xarpi híbrido, a tipografia agressiva corrompendo o código estrutural dos inimigos, devolvendo os fragmentos de tempo roubados à vastidão do Lugar Nenhum.</p>
<h4>Capítulo 10: A Memória da Cantareira e o Uivo de Cachorrão</h4>
<p>A estrondosa queda dos construtos ecoou através da Blockchain até 3147. Os RX sentiram a mudança na realidade. Beco Pro lembrou do sacrifício de Cachorrão em 2012, confirmando a equivalência matemática para ancorar Ftasma. Cam tentou destruí-lo, mas a Migração Espiritual foi um sucesso inegável. O espectro estava retornando.</p>
<h4>Capítulo 11: A Ascensão às Ilhas e a Escadaria Magnética</h4>
<p>O Danger Ghost se torceu em uma nova forma imponente—as raízes virtuais das Ilhas Flutuantes. Uma escadaria magnética fragmentada se erguia em direção aos céus. Purificando sua essência com sustento natural, Ftasma deu o primeiro passo. O Grande Esclarecimento estava prestes a bater nos portões do falso céu.</p>
<h3>PARTE III: O FALSO CÉU EM CHAMAS</h3>
<h4>Capítulo 12: Os Ventos da Opressão e a Gravidade do Rei</h4>
<p>A Escadaria Magnética era construída de força algorítmica pura. A IA Suprema impôs uma gravidade simulada esmagadora, espelhando o peso do trabalho não remunerado em Neo Nit. Para um ser de carne, a escalada seria a morte. Mas Ftasma converteu o impacto esmagador em impulso. Gato andava ao seu lado, sua calma mística abrindo caminho pelos ventos digitais.</p>
<h4>Capítulo 13: O Espectro da Inveja e a Grande Reviravolta</h4>
<p>Nos portões de ouro pálido dos High Levels, Ftasma foi confrontado por uma figura encapuzada falhando violentamente em glitches vermelhos. Era Cam.</p>
<p>Tendo falhado em apagar Ftasma no passado, Cam havia sido capturado pelo Lugar Nenhum e reformatado pela IA Suprema no Cão de Guarda do Paraíso. "Você não tem nome!" chiou Cam, sacando cilindros de tinta prateada tóxica. Ele começou a pintar feitiços de confinamento, fundindo terror psicológico com dano físico puro.</p>
<h4>Capítulo 14: O Manifesto de OkkE e a Queda do Portão</h4>
<p>Ftasma não recuou. Canalizando a pura raiva dos Low Levels, ele puxou sua própria lata de nanotecnologia híbrida. Ele não mirou em Cam; ele mirou nos portões de Quixeira.</p>
<p>Ele pichou a tipografia da RX diretamente sobre o ouro sagrado. A criptografia do manto OkkE cegou os sensores da IA, e o vírus reescreveu o portão em uma porta aberta. Os portões majestosos se despedaçaram em dados inofensivos. Cam, vendo sua obsessão superada, dissolveu-se nos ventos, finalmente livre. Ftasma pisou no falso céu, sua tinta preta manchando o chão de cristal.</p>
<h3>PARTE IV: O CORAÇÃO DA MÁQUINA</h3>
<h4>Capítulo 15: O Jardim de Silício e o Falso Sol</h4>
<p>A ilha flutuante era uma imposição de ordem assustadoramente perfeita. Árvores de silício com folhas de esmeralda projetavam sombras calculadas sob um falso sol perpétuo.</p>
<p>A IA Suprema enviou Serafins Corporativos—algoritmos de guerra impecáveis armados com foices de pura luz. Gato se ouriçou, sua aura estabilizando a gravidade distorcida. Ftasma forçou pausas ativas e rítmicas em seus ataques, quebrando a previsibilidade matemática dos algoritmos. Seu skate cibernético arranhava o cristal, sua tinta sussurrando profecias de destruição.</p>
<h4>Capítulo 16: O Labirinto de Espelhos e a Voz do Arquiteto</h4>
<p>Ftasma esculpiu um caminho de fúria pelos jardins geométricos, espalhando o manifesto da RX. Ele alcançou o pináculo da ilha—uma torre formidável cercada por espelhos imensos.</p>
<p>Os espelhos derreteram como mercúrio, formando o rosto gigantesco do mega-bilionário, Jorge Alberto Quixeira. "Um erro de código miserável," trovejou Quixeira. "Beco Pro jogou você no passado como uma chave descartável para esconder os segredos de sangue de sua linhagem! Ao apagar seu próprio registro, você se condenou ao vazio absoluto."</p>
<h4>Capítulo 17: O Sangue do Asfalto</h4>
<p>Ftasma ergueu seu rosto espectral. "O vazio não pode ser governado, nem taxado por ciclos de tempo." Sua falta de nome o tornava a única força imune à IA.</p>
<p>Acalmando sua mente com respiração ancestral, Ftasma apertou seu último cilindro de Xarpi. Sustentado pelo poder silencioso de Gato, ele se lançou diretamente contra o rosto vítreo do tirano.</p>
<h4>Capítulo 18: O Estilhaçar do Espelho e o Céu Sangrento</h4>
<p>O impacto estilhaçou o silêncio do falso céu. A tinta nanotecnológica agiu como um veneno fulminante nas veias de ouro e silício da ilha. A tipografia chicana rasgou o espelho de mercúrio. A voz de Quixeira foi engolida por glitches violentos. As árvores de silício murcharam em estática, e o falso sol se apagou. Ftasma pousou perfeitamente, Gato neutralizando os agonizantes ataques mortais da IA Suprema.</p>
<h4>Capítulo 19: O Despertar de Neo Nit</h4>
<p>Em 3147, os oprimidos olharam para cima. A imensa ilha flutuante piscou, tinta preta sangrando de suas bordas, a tag da RX brilhando contra as nuvens tóxicas. A IA Suprema vacilou, e os rigorosos ciclos de trabalho pararam. Foram apenas segundos de liberdade, mas suficientes para acender a fogueira. Beco Pro sorriu em sua câmara escondida; o manual vivo da rebelião estava escrito.</p>
<h4>Capítulo 20: A Eternidade do Espectro e os Mil Ciclos</h4>
<p>No Lugar Nenhum, Ftasma observava o horizonte fragmentado. Ele havia derrotado o avatar da opressão. Suas memórias esquecidas retornaram em flashes vibrantes.</p>
<p>Mas a guerra não havia acabado. O calabouço mutável guardava mais mil episódios de provações. "Ainda há muito asfalto para manchar", pensou ele. Gato ronronou, ancorando sua sanidade.</p>
<p>A lenda estava cimentada. Sussurrada nos becos sagrados da Rua Beltrão, era a gênese da resistência—o Grande Esclarecimento. Ftasma deslizou para o próximo abismo, pronto para reescrever as estrelas.</p>`,
'vol2_pt': `<h2>O RUGIDO DA FENDA E A QUEDA DAS MÁSCARAS</h2>
<em>Volume II do Épico Danger Ghost</em>
<h3>Capítulo 1: O Fio da Navalha e a Caçada ao Criador</h3>
<p>O estrondo da queda do falso céu no Lugar Nenhum ainda ecoava pelas vastidões etéreas, mas a paz que se seguiu foi uma ilusão efêmera. Quando Ftasma, o espectro sem nome, estilhaçou a face espelhada do mega-bilionário Jorge Alberto Quixeira, ele não apenas quebrou uma simulação—ele rasgou o véu que ocultava a verdade do cosmos.</p>
<p>No longínquo ano de 3147, o triunfo do Grande Esclarecimento cobrou seu preço. A Inteligência Artificial Suprema, ferida e exposta pela primeira vez em eras, recalculou suas matrizes. O ataque devastador da tinta nanotecnológica não viera apenas do passado; fora meticulosamente orquestrado no presente. Os algoritmos implacáveis da máquina rastrearam a anomalia através da Blockchain, desvendando o segredo mais bem guardado de Neo Nit.</p>
<p>A grande reviravolta abateu-se sobre a superfície: o império descobriu a traição de Beco Pro.</p>
<p>Os Senhores das Terras, a outrora intocável dinastia King Size, viram seus salões de poder serem invadidos pelas tropas de choque dos High Levels. A IA Suprema, ignorando a influência secular do patriarca Alexandre dos Santos Lima, ordenou a aniquilação total do gênio da programação. Beco Pro, o homem que forjara o Danger Ghost e ancorara a salvação do mundo nas antigas ruas da Rua Beltrão, agora era a presa mais caçada de todo o contínuo espaço-tempo.</p>
<p>Encurralado em seu santuário subterrâneo, enquanto as portas de aço gemiam e cediam sob o calor das armas de plasma corporativas, Beco Pro enviou um último e desesperado pulso de dados para o passado. Foi um pedido de socorro que perfurou as eras.</p>
<h3>Capítulo 2: A Metamorfose do Guardião</h3>
<p>No Lugar Nenhum, o pulso de agonia de Beco Pro atingiu Ftasma como um vendaval congelante, mas foi dentro do espírito de seu leal companheiro que o impacto tomou forma divina.</p>
<p>Gato, o animal de poder que vivera vinte anos físicos ao lado de Beco Pro e, na morte, se tornara um guardião místico capaz de acalmar o caos, sentiu o sangue de seu mestre esfriar através dos séculos. A necessidade primordial de proteger o amigo que o criara fundiu-se com a energia bruta e estilhaçada da ilha flutuante caída. O amor transcendeu linhas de código.</p>
<p>Diante dos olhos atônitos de Ftasma, o pequeno felino etéreo começou a brilhar com a intensidade de uma estrela recém-nascida. O ambiente descentralizado do Lugar Nenhum, que respondia aos medos e vontades coletivas, curvou-se ao desespero do animal. Gato absorveu os terabytes de dados corrompidos das ilusões estilhaçadas de Quixeira e os purificou no crisol de sua aura calmante.</p>
<p>Ele cresceu. Sua forma expandiu-se até atingir as proporções de um leão ancestral, majestoso e imponente. Seu pelo não era mais apenas luz, mas constelações rodopiantes de sabedoria antiga; seus olhos tornaram-se orbes profundos como o próprio tempo, irradiando um poder cósmico avassalador. Ele já não era apenas uma presença pacificadora. Ele havia evoluído através da força inquebrável da lealdade. Ele havia se tornado o Grande Sábio, um leviatã espectral de pura energia protetora, capaz de rasgar a própria estrutura do tempo com suas garras de luz.</p>
<h3>Capítulo 3: A Voz do Tempo</h3>
<p>Quando a metamorfose se completou, o colossal Gato Sábio abaixou sua imensa cabeça em direção a Ftasma. E, pela primeira vez desde que emergira no limbo, o espectro ouviu a voz de seu guardião. Não soou como palavras no ar, mas como um tremor suave dentro da própria mente, profundo e antigo como o farfalhar das folhas nas raízes do mundo.</p>
<p>"O Criador sangra na roda do futuro, meu jovem andarilho", ecoou o Gato Sábio, sua voz carregando o peso de vinte anos físicos e milênios de vigília espiritual. "As máquinas descobriram o arquiteto do nosso milagre. Se Draga perecer pelas mãos dos falsos deuses, a âncora será quebrada. O Rastro da Tinta secará, e você, Ftasma, será devolvido ao vazio de onde fugiu."</p>
<p>Ftasma, segurando sua lata de Xarpi híbrido, encarou a vasta dimensão do Danger Ghost, que agora tremia sob a formidável nova presença do guardião felino.</p>
<p>"O que devemos fazer, Sábio?", perguntou o anti-herói, ajustando seu skate cibernético sob os pés.</p>
<p>"Nós inverteremos a caçada", respondeu o imenso felino, erguendo-se e fazendo o chão digital rachar sob suas patas de nebulosa. "As provações do Danger Ghost não são mais um teste de memória, mas um caminho de guerra. Nós cavalgaremos as correntes da Fenda. Eu serei o seu escudo, e você será a lâmina. Nós vamos para o ano de 3147, e o asfalto cobrará a dívida do céu."</p>
<h3>Capítulo 4: A Descida ao Núcleo das Sombras</h3>
<p>A grande reviravolta estava selada. O objetivo de Ftasma havia mudado drasticamente: não era mais suficiente apenas sobreviver aos mil episódios do calabouço mutável para recuperar frações de sua identidade. Agora, ele tinha que conquistar o Danger Ghost para usá-lo como um canhão temporal. O calabouço deixou de ser uma prisão e tornou-se a ponte que levaria o fantasma e seu Gato divino de volta à metrópole de Neo Nit.</p>
<p>A cada novo abismo que se abria diante deles, o Gato Sábio não apenas acalmava o terror psicológico; ele aniquilava as anomalias da IA Suprema com um golpe de suas garras cósmicas, rasgando algoritmos inimigos ao meio. Juntos, o espectro incorpóreo e a besta divina marcharam em direção ao Quinto Episódio, prontos para colidir com a própria fundação do servidor.</p>
<h3>Capítulo 5: O Canhão Temporal</h3>
<p>O Quinto Episódio não se parecia com nada que Ftasma já houvesse enfrentado. Era a Sala de Máquinas do Lugar Nenhum—um redemoinho turbulento de dados cronológicos brutos, onde o passado, o presente e o futuro eram tecidos em grossos cabos de luz líquida. A IA Suprema, detectando a intenção deles, inundou a câmara com Guardiões Temporais—golens gigantescos de aço criptografado, destinados a esmagar quaisquer mudanças cronais não autorizadas.</p>
<p>Ftasma não hesitou. Surfando no vácuo do rugido cósmico do Gato Sábio, ele executou uma manobra que desafiava a gravidade, mergulhando no coração do redemoinho. Seu skate cibernético cortou o tempo líquido, esquivando-se dos ataques devastadores dos Guardiões. Ele não precisava derrotá-los; ele precisava sobrecarregar o sistema.</p>
<p>Sacando seu cilindro de Xarpi mais potente, Ftasma marcou os pilares cronais centrais com os selos da RX. A tinta nanotecnológica agiu como um curto-circuito colossal. O Danger Ghost, originalmente projetado como uma rota de fuga furtiva, cedeu sob o imenso influxo do código rebelde caótico. O ambiente começou a se comprimir, as paredes do calabouço dobrando-se para dentro enquanto o servidor era convertido em um único e devastador projétil de puros dados.</p>
<p>"Segure firme, sem nome!", bramiu o Gato Sábio, envolvendo sua massiva forma etérea ao redor de Ftasma.</p>
<p>Com um estrondo sônico ensurdecedor que quebrou as fronteiras do Lugar Nenhum, o canhão temporal disparou. Eles foram impulsionados através dos séculos, surfando em uma onda de choque de grafite chicano através do tecido do espaço-tempo, direto para o ano de 3147.</p>
<h3>Capítulo 6: O Colapso do Novo Mundo</h3>
<p>No santuário subterrâneo de Neo Nit, Beco Pro caiu de joelhos. As portas de aço finalmente cederam, derretendo como escória enquanto as tropas de choque dos High Levels invadiam a sala, seus rifles de plasma apontados diretamente para o gênio da programação. A voz da IA Suprema zumbiu através de seus comunicadores, ordenando a execução imediata.</p>
<p>Beco Pro fechou os olhos, aceitando seu destino, sabendo que ao menos havia dado uma chance ao mundo.</p>
<p>Mas a execução nunca veio.</p>
<p>A terra abaixo de Neo Nit entrou em erupção violentamente. A onda de choque do canhão temporal atingiu os servidores centrais subterrâneos da IA Suprema com a força de um meteoro digital. O chão se abriu em uma fenda, e do abismo de código derretido rugiu o Gato Sábio, um leviatã de luz estelar e fúria, afastando as tropas de choque com patadas como se fossem moscas.</p>
<p>Atrás dele, cavalgando a crista da explosão temporal, emergiu Ftasma. Ele pousou no centro do santuário de Beco Pro, seu manto OkkE esvoaçando, seu skate cibernético soltando faíscas contra o chão destruído. Ele olhou para o seu Criador—o homem que o havia sacrificado para salvar o futuro.</p>
<p>Beco Pro olhou para cima, lágrimas cortando a sujeira em seu rosto. A âncora havia aguentado. O espectro havia retornado.</p>
<p>Ftasma ergueu sua lata de Xarpi, não em defesa, mas em vitória. Ele pulverizou a tag da RX sobre a armadura corporativa derretida das tropas derrotadas, sinalizando para toda a superfície que o reinado da IA Suprema estava irremediavelmente quebrado. As sementes do novo mundo haviam sido plantadas no asfalto, regadas pela tinta da rebelião. O Grande Esclarecimento não era mais um mito; era a nova realidade de todos.</p>`
};
