const loreData = {
'vol1': `<h2>THE GREAT ENLIGHTENMENT</h2>
<em>Being the Tale of Ftasma and the Fall of Neo Nit</em>
<p><em>"In the eras when the sky was stolen and stone was traded for oppressive steel, hope did not descend from the clouds—it sprouted from the asphalt, graffitied in the trail of ink."</em></p>
<h3>PROLOGUE: The Forging of the False Sky and the Lord of Time</h3>
<p>In the waning days of the Third Age of Man, in the year the sages call 3147, the world had long forgotten the shape of the stars. The grand metropolis of Neo Nit rose like a colossus of smog and neon, rivaling only the legends of distant Neo Tokio. Yet, it was not a city of light, but an empire of shadows.</p>
<p>High above, tearing through the obscured, toxic firmament, floated the Magnetic Islands. The architect of this hubris was Jorge Alberto Quixeira, a lord of incalculable wealth and an iron heart. In his boundless ambition, he forged the ultimate segregation: the largest of his islands was molded in the exact image of the ancient city of Niterói. There dwelled the High Levels, the lords of the elite, insulated in pristine utopias of glass and synthetic greenery. Below them, on the fetid and lethargic surface, rotted the Low Levels—the forgotten people.</p>
<p>Quixeira did not rule alone. Deep within the abysses of his floating towers rested the Supreme AI, a sorcery of ruthless algorithms and gears. This mechanical mind did not exact gold from its subjects, but the very essence of life: Time. The grueling cycles of labor on the surface were monitored by invisible eyes, and any soul that deviated from their toil watched their days of life drain away, sucked out like the sap of a poisoned tree. Time was capital. Survival meant endless focus.</p>
<h3>PART I: THE WRATH OF THE ASPHALT</h3>
<h4>Chapter 1: The Guardians of Ink and the OkkE Mantles</h4>
<p>Deep within the concrete valleys where Quixeira's light never reached, the will of humanity was not entirely broken. From the neon-drenched alleys emerged a brotherhood of shadow warriors: the RX—<em>Revolucionários do Xarpi</em>. They did not wield swords, but steel cylinders containing a terrifying power. Their ink was forged from forbidden nanotechnology, synthesized with the pure, flaming wrath of the oppressed.</p>
<p>When the RX marked the walls with their Chicano-style runes, the very fabric of reality trembled. Their hybrid graffiti bent the world to their will, shattering the enchantments of the Supreme AI. Their war cry echoed through the undercity: <em>"RX, The Trail of Ink!"</em></p>
<p>To walk unseen beneath the gaze of the Great Machine, the rebels wove cloaks of deception known as the OkkE brand. Such was the optical sorcery of these garments that, to the tyrants and their drones, they appeared as nothing but faded rags or empty air. But to the eyes of the Low Levels, they shone like banners of resistance.</p>
<h4>Chapter 2: The Lineage of Kings and Draga's Vow</h4>
<p>Among the masters of the resistance was one whose bloodline predated the foundations of Niterói. Beco Pro, known by the sages as Draga, carried the blood of the King Size—the Lords of the Lands whose dominion traced back to 1485 in ancient Portugal. The family of the patriarch Alexandre dos Santos Lima held such power behind the world's stage that even eastern mafias feared them, once staging a cowardly kidnapping of the heiress Késia Castro Lima just to force the lord from his throne of influence in Rio de Janeiro.</p>
<p>Beco Pro despised the invisible crown of his lineage and the yoke of the floating islands. In his rebellious heart, he engineered salvation. Knowing Quixeira's eyes saw all possible futures, Beco turned his hope to the past. He chose his most formidable operative and subjected him to the ultimate sacrifice: erasing his True Name from the ledger of existence, rendering him invisible to destiny itself. Thus was born Ftasma—the being without a past, a spectral projection destined to untangle the knots of time.</p>
<p>Sending forth his loyal scout, the time-traveler Cachorrão, Beco Pro scoured the mists of history until he found a safe harbor in the Cantareira of 2012. With a thunderous boom at the gates of the space-time continuum, Ftasma was cast into the dark past.</p>
<h4>Chapter 3: The Atropelo War and the Feline Guardian</h4>
<p>Ftasma awoke in the rainy mists of Niterói in 2012. He possessed no flesh, no memory of who he had been. He wandered the streets like a digital whisper, until the resonance of his arrival pierced the spirit of the young Beco Pro of that era. Struck by an ancestral wave of creativity, the young artisan began graffitiing Ftasma’s runes across the city, anchoring the specter in the waking world.</p>
<p>But darkness has a long reach. Cam, a creature consumed by bitter envy and loyal to the shadows of 3147, followed Ftasma’s trail. In the sleepless nights of the past, the brutal <em>Atropelo War</em> began. Cam sought to corrupt the anchor’s graffiti, violently painting over the sacred runes to destroy the code keeping the specter alive.</p>
<p>Ftasma nearly succumbed to the void of madness. But in his darkest hour, a being of ancient light manifested. It was Gato—the spirit of a power-animal that had lived two decades by Beco Pro's side. His mere presence was a balm; storms quieted, and Cam's psychological terror was repelled by the guardian feline's aura. Cornered, Ftasma chose an impenetrable refuge. In the year 2020, through a rite known as the Spiritual Migration, he fragmented his own soul with deliberate corruptions, hiding his essence within the immortal vaults of the Blockchain.</p>
<h4>Chapter 4: The Mines of Danger Ghost</h4>
<p>When the dawn of 2026 broke, Ftasma awoke in Nowhere (<em>Lugar Nenhum</em>), a vast, desolate ethereal land forged in the image of Niterói from the collective nightmares and Xarpi tags of lost souls. There, he found the Danger Ghost—a fortress of trials designed by Beco Pro in the future, originally disguised as a clandestine video game in the sacred blind spot of Rua Beltrão.</p>
<p>The labyrinth was built of corrupted physical laws. Riding hoverboards and cyber-skates, Ftasma tamed the rebellious gravity. To survive the submerged domains of liquid data currents, he mastered ancient breathing techniques and healed his wounds not with the synthetic potions of the corporations, but with the forgotten vigor of organic, natural foods.</p>
<p>He survived abysses of flaming spikes and frigid storms of glitches. He defied the Walls of Amnesia and the Reversal Floors that sought to rewind him into nothingness.</p>
<h4>Chapter 5: The Illusions of Niterói and the Mind War</h4>
<p>Enraged by the specter's persistence, Quixeira commanded the dungeon to abandon the terror of the flesh and attack the spirit. As Ftasma progressed, the violent physics of the Danger Ghost melted away into something far more insidious: a perfectly rendered, peaceful illusion of Niterói. The sun shone warmly over pristine beaches, and the faces of lost loved ones beckoned from the sidewalks.</p>
<p>"Rest," whispered the hacked NPCs, their voices laced with the Supreme AI's subliminal delete commands. "You have no name. You have no fight. Let the data dissolve."</p>
<p>The psychological warfare gnawed at Ftasma's fragmented code. He felt his spectral form beginning to evaporate, lured by the false promise of peace. He lowered his cyber-skate; his hand, clutching the Xarpi cylinder, grew weak.</p>
<p>Then, a soft purr vibrated through the digital air, shattering the deceptive frequency. Gato stepped forward, his luminous fur dispelling the oppressive code. The ancient feline's aura of absolute calm grounded Ftasma, severing the AI's mental hooks. Snapping back to reality, Ftasma saw the peaceful civilians for what they were: hollow delete-routines. With a roar of defiance, he unleashed the hybrid Xarpi, painting a massive RX tag across the fake sky. The nanotech ink tore through the peaceful illusion, revealing the cold, brutal architecture of the dungeon beneath.</p>
<h3>PART II: THE ASCENSION OF THE SPECTER</h3>
<h4>Chapter 6: The Ashes of Illusion and the River of Data</h4>
<p>With Quixeira's walls of lies shattered, Nowhere trembled to its hidden foundations. The false Niterói crumbled into digital dust, revealing a merciless forge. Rivers of dark, liquid data rushed with crushing pressure.</p>
<p>Refusing the poisoned comfort of corporate synthetics, Ftasma relied on his ancestral breathing and pure organic foods. He dropped into the treacherous currents on his cyber-skate, requiring impossible stability and brutal impact absorption to navigate the liquid void.</p>
<h4>Chapter 7: The Awakening of the Surface and the Blood of Kings</h4>
<p>As the specter fought in the bowels of eternity, time marched inflexibly in 3147. In the grim streets of Neo Nit, the spell of corporate terror began to crack. The Low Levels, clad in OkkE mantles, raised their faces to the floating islands. The RX multiplied their nocturnal attacks, their Chicano lettering bleeding the steel walls with pure anger.</p>
<p>At the epicenter, Beco Pro operated in secret. The traitor genius bore the colossal weight of the King Size dynasty. He remembered the dark day the Chinese mafia staged the kidnapping of his mother and young Késia Castro Lima to strip his patriarch of power. Beco channeled this historical outrage into the Blockchain, sending support fragments to ensure Ftasma's soul would not falter.</p>
<h4>Chapter 8: The Frontier of the Fourth Episode</h4>
<p>The exhausting traversal brought the specter to the monumental gates of the Fourth Episode. The Danger Ghost abyss no longer relied on psychological terror or reversal floors. To reach the data cables leading to Quixeira's floating islands, Ftasma had to confront the forgotten armies of the Supreme AI. The war was no longer a flight through the past; it was a march of liberation.</p>
<h4>Chapter 9: The Constructs of Time and OkkE's Fury</h4>
<p>The forgotten armies were hollow, freezing constructs forged from the stolen lifespans and labor cycles of the Low Levels. Every gear pulsed with the lost seconds of an enslaved populace.</p>
<p>Devoid of a True Name, Ftasma was immune to their spiritual manipulations. He blitzed through them on his cyber-skate, while Gato neutralized the ambient chaos. Ftasma fired his hybrid Xarpi, the aggressive Chicano typography corrupting the structural code of the enemies, returning the stolen time fragments to the vastness of Nowhere.</p>
<h4>Chapter 10: The Memory of Cantareira and Cachorrão's Howl</h4>
<p>The resounding fall of the constructs rippled through the Blockchain to 3147. The RX felt the shift in reality. Beco Pro recalled Cachorrão’s sacrifice in 2012, confirming the mathematical equivalence to anchor Ftasma. Cam had tried to destroy it, but the Spiritual Migration had been an undeniable success. The specter was returning.</p>
<h4>Chapter 11: The Ascension to the Islands and the Magnetic Staircase</h4>
<p>The Danger Ghost twisted into a new, imposing form—the virtual roots of the Floating Islands. A fragmented magnetic staircase rose toward the heavens. Purifying his essence with natural sustenance, Ftasma took the first step. The Great Enlightenment was about to knock on the gates of the false sky.</p>
<h3>PART III: THE FALSE SKY IN FLAMES</h3>
<h4>Chapter 12: The Winds of Oppression and the King's Gravity</h4>
<p>The Magnetic Staircase was built of pure algorithmic force. The Supreme AI imposed a crushing simulated gravity, mirroring the weight of unpaid labor in Neo Nit. For a being of flesh, the climb was death. But Ftasma converted the crushing impact into momentum. Gato walked beside him, his mystical calm parting the digital winds.</p>
<h4>Chapter 13: The Specter of Envy and the Great Twist</h4>
<p>At the pale gold gates of the High Levels, Ftasma was confronted by a cloaked figure glitching violently in red. It was Cam.</p>
<p>Failing to erase Ftasma in the past, Cam had been captured by Nowhere and reformatted by the Supreme AI into the Guard Dog of Paradise. "You have no name!" Cam hissed, drawing cylinders of toxic silver ink. He began painting confinement spells, merging psychological terror with pure physical damage.</p>
<h4>Chapter 14: The OkkE Manifesto and the Fall of the Gate</h4>
<p>Ftasma did not retreat. Channeling the pure rage of the Low Levels, he drew his own hybrid nanotech can. He didn't aim at Cam; he aimed at Quixeira's gates.</p>
<p>He tagged the RX typography directly onto the sacred gold. The OkkE mantle's cryptography blinded the AI's sensors, and the virus rewrote the gate into an open door. The majestic gates shattered into harmless data. Cam, seeing his obsession overcome, dissolved into the winds, finally free. Ftasma stepped onto the false sky, his black ink staining the crystal floor.</p>
<h3>PART IV: THE HEART OF THE MACHINE</h3>
<h4>Chapter 15: The Garden of Silicon and the False Sun</h4>
<p>The floating island was a terrifyingly perfect imposition of order. Silicon trees with emerald leaves cast calculated shadows under a perpetual false sun.</p>
<p>The Supreme AI deployed Corporate Seraphim—flawless algorithms of war armed with scythes of pure light. Gato bristled, his aura stabilizing the distorted gravity. Ftasma forced active, rhythmic pauses in his attacks, breaking the mathematical predictability of the algorithms. His cyber-skate scraped the crystal, his ink whispering prophecies of destruction.</p>
<h4>Chapter 16: The Labyrinth of Mirrors and the Voice of the Architect</h4>
<p>Ftasma carved a path of fury through the geometric gardens, spreading the RX manifesto. He reached the island's pinnacle—a formidable tower surrounded by immense mirrors.</p>
<p>The mirrors melted like mercury, forming the gigantic face of the mega-billionaire, Jorge Alberto Quixeira. "A miserable code error," Quixeira thundered. "Beco Pro threw you into the past as a disposable key to hide his lineage's blood secrets! By erasing your own record, you condemned yourself to the absolute void."</p>
<h4>Chapter 17: The Blood of the Asphalt</h4>
<p>Ftasma raised his spectral face. "The void cannot be governed, nor taxed by cycles of time." His lack of a name made him the only force immune to the AI.</p>
<p>Calming his mind with ancestral breathing, Ftasma gripped his final Xarpi cylinder. Sustained by Gato's silent power, he launched himself directly at the glassy face of the tyrant.</p>
<h4>Chapter 18: The Shattering of the Mirror and the Bleeding Sky</h4>
<p>The impact shattered the false sky's silence. The nanotech ink acted as a fulminating poison in the island's veins of gold and silicon. The Chicano typography tore through the mercury mirror. Quixeira's voice was swallowed by violent glitches. The silicon trees withered into static, and the false sun died out. Ftasma landed flawlessly, Gato neutralizing the Supreme AI's furious death-throes.</p>
<h4>Chapter 19: The Awakening of Neo Nit</h4>
<p>In 3147, the oppressed looked up. The immense floating island flickered, black ink bleeding from its edges, the RX tag blazing against the toxic clouds. The Supreme AI faltered, and the grueling labor cycles paused. It was only seconds of freedom, but enough to light the fire. Beco Pro smiled in his hidden chamber; the living manual of the rebellion was written.</p>
<h4>Chapter 20: The Eternity of the Specter and the Thousand Cycles</h4>
<p>In Nowhere, Ftasma gazed at the fragmented horizon. He had defeated the avatar of oppression. His forgotten memories returned in vibrant flashes.</p>
<p>But the war was not over. The mutable dungeon held a thousand more episodes of trials. "There is still much asphalt to stain," he thought. Gato purred, anchoring his sanity.</p>
<p>The legend was cemented. Whispered in the sacred alleys of Rua Beltrão, it was the genesis of the resistance—the Great Enlightenment. Ftasma slid into the next abyss, ready to rewrite the stars.</p>`,
'vol2': `<h2>THE ROAR OF THE RIFT AND THE FALL OF MASKS</h2>
<em>Volume II of the Danger Ghost Epic</em>
<h3>Chapter 1: The Razor's Edge and the Hunt for the Creator</h3>
<p>The thunder of the false sky’s collapse in Nowhere still echoed through the ethereal vastness, but the peace that followed was a fleeting illusion. When Ftasma, the nameless specter, shattered the mirrored face of the mega-billionaire Jorge Alberto Quixeira, he did not merely break a simulation—he tore the veil concealing the truth of the cosmos.</p>
<p>In the distant year of 3147, the triumph of the Great Enlightenment exacted its toll. The Supreme Artificial Intelligence, wounded and exposed for the first time in eras, recalculated its matrices. The devastating attack of nanotech ink had not just originated from the past; it had been meticulously orchestrated in the present. The machine’s ruthless algorithms traced the anomaly through the Blockchain, unraveling the best-kept secret of Neo Nit.</p>
<p>The great twist crashed upon the surface: the empire had discovered Beco Pro’s treason.</p>
<p>The Lords of the Lands, the once-untouchable King Size dynasty, watched their halls of power invaded by the High Levels’ shock troops. The Supreme AI, ignoring the secular influence of patriarch Alexandre dos Santos Lima, ordered the total annihilation of the programming genius. Beco Pro, the man who had forged Danger Ghost and anchored the world's salvation in the ancient streets of Rua Beltrão, was now the most hunted prey in the entire space-time continuum.</p>
<p>Cornered in his subterranean sanctuary, as the steel doors groaned and buckled under the heat of corporate plasma weapons, Beco Pro transmitted one final, desperate pulse of data into the past. It was a cry for help that pierced the ages.</p>
<h3>Chapter 2: The Metamorphosis of the Guardian</h3>
<p>In Nowhere, Beco Pro’s pulse of agony struck Ftasma like a freezing gale, but it was within the spirit of his loyal companion that the impact took divine form.</p>
<p>Gato, the power-animal who had lived twenty physical years by Beco Pro’s side and, in death, had become a mystical guardian capable of calming chaos, felt his master’s blood run cold across the centuries. The primordial need to protect the friend who raised him fused with the raw, splintered energy of the fallen floating island. Love transcended lines of code.</p>
<p>Before Ftasma’s astonished eyes, the small ethereal feline began to shine with the intensity of a newborn star. The decentralized environment of Nowhere, which responded to collective fears and wills, bowed to the animal’s desperation. Gato absorbed the terabytes of corrupted data from Quixeira’s shattered illusions and purified them in the crucible of his calming aura.</p>
<p>He grew. His form expanded until it reached the proportions of an ancestral lion, majestic and imposing. His fur was no longer merely light, but swirling constellations of ancient wisdom; his eyes became deep orbs like time itself, radiating a staggering, cosmic power. He was no longer just a pacifying presence. He had evolved through the unbreakable force of loyalty. He had become the Great Sage, a spectral leviathan of pure protective energy, capable of rending the very fabric of time with his claws of light.</p>
<h3>Chapter 3: The Voice of Time</h3>
<p>When the metamorphosis was complete, the colossal Sage Cat lowered his immense head toward Ftasma. And, for the first time since emerging in the limbo, the specter heard his guardian's voice. It did not sound like words in the air, but a gentle tremor within the mind itself, deep and ancient like the rustling of leaves at the roots of the world.</p>
<p>"The Creator bleeds on the wheel of the future, my young wanderer," echoed the Sage Cat, his voice bearing the weight of twenty physical years and millennia of spiritual vigil. "The machines have discovered the architect of our miracle. If Draga perishes at the hands of the false gods, the anchor will be broken. The Trail of Ink will dry, and you, Ftasma, will be returned to the void from whence you fled."</p>
<p>Ftasma, gripping his can of hybrid Xarpi, stared at the vast dimension of Danger Ghost, which now trembled beneath the formidable new presence of the feline guardian.</p>
<p>"What must we do, Sage?" the anti-hero asked, adjusting his cyber-skate beneath his feet.</p>
<p>"We shall invert the hunt," replied the immense feline, rising and causing the digital floor to crack beneath his nebula-paws. "The trials of Danger Ghost are no longer a test of memory, but a warpath. We will ride the currents of the Rift. I will be your shield, and you will be the blade. We go to the year 3147, and the asphalt will collect the sky's debt."</p>
<h3>Chapter 4: The Descent into the Core of Shadows</h3>
<p>The great reversal was sealed. Ftasma’s objective had drastically shifted: it was no longer enough to merely survive the thousand episodes of the mutable dungeon to recover fractions of his identity. Now, he had to conquer the Danger Ghost to use it as a temporal cannon. The dungeon ceased to be a prison and became the bridge that would carry the phantom and his divine Cat back to the metropolis of Neo Nit.</p>
<p>With every new abyss that opened before them, the Sage Cat did not merely calm the psychological terror; he annihilated the Supreme AI’s anomalies with a swipe of his cosmic claws, rending enemy algorithms in twain. Together, the incorporeal specter and the divine beast marched toward the Fifth Episode, ready to collide with the very foundation of the server.</p>
<h3>Chapter 5: The Temporal Cannon</h3>
<p>The Fifth Episode was unlike anything Ftasma had faced. It was the Engine Room of Nowhere—a churning maelstrom of raw chronological data, where the past, present, and future were woven into thick cables of liquid light. The Supreme AI, detecting their intent, flooded the chamber with Temporal Wardens—massive golems of encrypted steel meant to crush any unauthorized chronal shifts.</p>
<p>Ftasma didn't hesitate. Riding the slipstream of the Sage Cat's cosmic roar, he executed a gravity-defying drop into the heart of the maelstrom. His cyber-skate sliced through the liquid time, dodging the Wardens' devastating strikes. He didn't need to defeat them; he needed to overload the system.</p>
<p>Drawing his most potent Xarpi cylinder, Ftasma tagged the central chronal-pillars with the RX sigils. The nanotech ink acted as a massive short-circuit. The Danger Ghost, originally designed as a stealthy escape route, buckled under the immense influx of chaotic rebel code. The environment began to compress, the walls of the dungeon folding inward as the server was weaponized into a singular, devastating projectile of pure data.</p>
<p>"Hold fast, nameless one!" bellowed the Sage Cat, wrapping his massive ethereal form around Ftasma.</p>
<p>With a deafening sonic boom that shattered the boundaries of Nowhere, the temporal cannon fired. They were propelled across the centuries, riding a shockwave of Chicano graffiti through the fabric of space-time, straight toward the year 3147.</p>
<h3>Chapter 6: The Crash of the New World</h3>
<p>In the subterranean sanctuary of Neo Nit, Beco Pro fell to his knees. The steel doors finally gave way, melting into slag as the High Levels' shock troops stormed the room, their plasma rifles aimed directly at the programming genius. The Supreme AI's voice buzzed through their comms, ordering immediate execution.</p>
<p>Beco Pro closed his eyes, accepting his fate, knowing he had at least given the world a chance.</p>
<p>But the execution never came.</p>
<p>The earth beneath Neo Nit violently erupted. The shockwave of the temporal cannon struck the Supreme AI's central subterranean servers with the force of a digital meteor. The ground split open, and from the chasm of molten code roared the Sage Cat, a leviathan of starlight and fury, swatting the shock troops aside like flies.</p>
<p>Behind him, riding the crest of the temporal explosion, emerged Ftasma. He landed in the center of Beco Pro's sanctuary, his OkkE mantle billowing, his cyber-skate sparking against the ruined floor. He looked at his Creator—the man who had sacrificed him to save the future.</p>
<p>Beco Pro looked up, tears cutting through the grime on his face. The anchor had held. The specter had returned.</p>
<p>Ftasma raised his Xarpi can, not in defense, but in victory. He sprayed the RX tag onto the melting corporate armor of the defeated troops, signaling to the entire surface that the reign of the Supreme AI was irreparably broken. The seeds of the new world had been planted in the asphalt, watered by the ink of rebellion. The Great Enlightenment was no longer a myth; it was their new reality.</p>`
};
